baseURL: https://aleshkev.github.io
languageCode: pl
DefaultContentLanguage: pl
title: aleshkev.github.io
params:
  author: Jonasz Aleszkiewicz

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Archiwum
      url: /posts/
      weight: 2
#    - name: O mnie
#      url: /o-mnie/
#      weight: 3
#    - name: Kontakt
#      url: /kontakt/
#      weight: 4

markup:
  highlight:
    style: monokailight
  goldmark:
    renderer:
      unsafe: true

related:
  threshold: 0
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 100
    - name: date
      weight: 10

permalinks:
  posts: "/:title"
#  meta: "/:title"

frontmatter:
  date:
    - :filename
    - :default
  lastmod:
    - lastmod
